services:
  backend:
    image: jjsalustiano/backend-java:latest
    container_name: dumply-backend
    ports:
      - "8080:8080"
    volumes:
      - /home/opc/app/wallet:/app/wallet
    environment:
      JAVA_OPTS: -Xms128m -Xmx200m
      SPRING_PROFILES_ACTIVE: prod
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PASSWORD: ${APP_PASSWORD}
      TNS_ADMIN: /app/wallet
      JWT_API_SECRET: ${JWT_API_SECRET}
    restart: unless-stopped

  frontend:
    image: jjsalustiano/frontend-react:latest
    container_name: dumply-frontend
    ports:
      - "80:80"
    restart: unless-stopped
