spring.application.name=dumply

### Configuracoes do Postgres (Render)
#spring.datasource.url=jdbc:postgresql://dpg-d5f069ngi27c73cdglrg-a/dumplydatabase_40m9
#spring.datasource.username=joca
#spring.datasource.password=1IgNjHNo2iomYmpVzObq5lWaLlZb0BPS
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Configuracoes do H2
spring.datasource.url=jdbc:h2:mem:financas_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#ENVIO DE EMAILS TESTE
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3de2c665d0b903
spring.mail.password=39ce8069d13e2a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Habilita o console do H2 no navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false
app.frontend.url=http://localhost:5173
jwt.api.secret=senhasupersecreta

